#!/bin/bash
# =============================================================================
# Helios Setup Script
# =============================================================================
# This script helps configure Helios with your GCP project settings.
#
# Usage: ./scripts/setup.sh <GCP_PROJECT_ID>
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if project ID is provided
if [ -z "$1" ]; then
    echo -e "${RED}Error: GCP Project ID is required${NC}"
    echo ""
    echo "Usage: ./scripts/setup.sh <GCP_PROJECT_ID>"
    echo ""
    echo "Example: ./scripts/setup.sh my-gcp-project-123456"
    exit 1
fi

GCP_PROJECT_ID="$1"
GCP_REGION="${2:-us-central1}"

echo -e "${GREEN}==============================================================================${NC}"
echo -e "${GREEN}Helios Setup${NC}"
echo -e "${GREEN}==============================================================================${NC}"
echo ""
echo "GCP Project ID: ${GCP_PROJECT_ID}"
echo "GCP Region:     ${GCP_REGION}"
echo ""

# Create .env file from template
echo -e "${YELLOW}Creating .env file...${NC}"
if [ -f ".env" ]; then
    echo -e "${YELLOW}Warning: .env file already exists. Creating .env.new instead.${NC}"
    ENV_FILE=".env.new"
else
    ENV_FILE=".env"
fi

cat > "$ENV_FILE" << EOF
# Helios Configuration
# Generated by setup.sh on $(date)

# GCP Configuration
GCP_PROJECT_ID=${GCP_PROJECT_ID}
GCP_REGION=${GCP_REGION}
GCP_ZONE=${GCP_REGION}-a

# Container Registry
CONTAINER_REGISTRY=gcr.io/${GCP_PROJECT_ID}

# GCS Buckets
MODELS_GCS_BUCKET=helios-models-${GCP_PROJECT_ID}
BILLING_DATASET=billing_export

# Kubernetes
GKE_CLUSTER_NAME=helios-dev-gke
HELIOS_NAMESPACE=helios

# Service Versions
HELIOS_INFERENCE_VERSION=0.2.0
HELIOS_COST_VERSION=0.1.0

# Monitoring
PROMETHEUS_URL=http://prometheus-server.monitoring.svc.cluster.local
GRAFANA_URL=http://grafana.monitoring.svc.cluster.local

# Environment
ENVIRONMENT=development
LOG_LEVEL=info
EOF

echo -e "${GREEN}Created ${ENV_FILE}${NC}"

# Update Kubernetes manifests
echo ""
echo -e "${YELLOW}Updating Kubernetes manifests...${NC}"

# Function to replace placeholder in files
replace_placeholder() {
    local file="$1"
    if [ -f "$file" ]; then
        sed -i "s/YOUR_GCP_PROJECT_ID/${GCP_PROJECT_ID}/g" "$file"
        echo "  Updated: $file"
    fi
}

# Update deployment files
replace_placeholder "infra/kubernetes/helios-inference/deployment.yaml"
replace_placeholder "infra/kubernetes/helios-inference/configmap.yaml"
replace_placeholder "infra/kubernetes/helios-cost/deployment.yaml"
replace_placeholder "infra/kubernetes/helios-cost/configmap.yaml"
replace_placeholder "infra/kubernetes/saleor/base/configmap.yaml"

echo ""
echo -e "${GREEN}==============================================================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${GREEN}==============================================================================${NC}"
echo ""
echo "Next steps:"
echo "  1. Review the generated .env file"
echo "  2. Set your GCP project: gcloud config set project ${GCP_PROJECT_ID}"
echo "  3. Authenticate: gcloud auth application-default login"
echo "  4. Create GCS bucket: gcloud storage buckets create gs://helios-models-${GCP_PROJECT_ID}"
echo "  5. Build and push images using Cloud Build"
echo ""
