# =============================================================================
# Helios Setup Script for Windows
# =============================================================================
# This script helps configure Helios with your GCP project settings.
#
# Usage: .\scripts\setup.ps1 -ProjectId <GCP_PROJECT_ID>
# =============================================================================

param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectId,
    
    [Parameter(Mandatory=$false)]
    [string]$Region = "us-central1"
)

$ErrorActionPreference = "Stop"

Write-Host "==============================================================================" -ForegroundColor Green
Write-Host "Helios Setup" -ForegroundColor Green
Write-Host "==============================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "GCP Project ID: $ProjectId"
Write-Host "GCP Region:     $Region"
Write-Host ""

# Create .env file from template
Write-Host "Creating .env file..." -ForegroundColor Yellow

$envFile = ".env"
if (Test-Path $envFile) {
    Write-Host "Warning: .env file already exists. Creating .env.new instead." -ForegroundColor Yellow
    $envFile = ".env.new"
}

$envContent = @"
# Helios Configuration
# Generated by setup.ps1 on $(Get-Date)

# GCP Configuration
GCP_PROJECT_ID=$ProjectId
GCP_REGION=$Region
GCP_ZONE=$Region-a

# Container Registry
CONTAINER_REGISTRY=gcr.io/$ProjectId

# GCS Buckets
MODELS_GCS_BUCKET=helios-models-$ProjectId
BILLING_DATASET=billing_export

# Kubernetes
GKE_CLUSTER_NAME=helios-dev-gke
HELIOS_NAMESPACE=helios

# Service Versions
HELIOS_INFERENCE_VERSION=0.2.0
HELIOS_COST_VERSION=0.1.0

# Monitoring
PROMETHEUS_URL=http://prometheus-server.monitoring.svc.cluster.local
GRAFANA_URL=http://grafana.monitoring.svc.cluster.local

# Environment
ENVIRONMENT=development
LOG_LEVEL=info
"@

Set-Content -Path $envFile -Value $envContent
Write-Host "Created $envFile" -ForegroundColor Green

# Update Kubernetes manifests
Write-Host ""
Write-Host "Updating Kubernetes manifests..." -ForegroundColor Yellow

function Update-Placeholder {
    param([string]$FilePath)
    
    if (Test-Path $FilePath) {
        $content = Get-Content -Path $FilePath -Raw
        $content = $content -replace "YOUR_GCP_PROJECT_ID", $ProjectId
        Set-Content -Path $FilePath -Value $content -NoNewline
        Write-Host "  Updated: $FilePath"
    }
}

Update-Placeholder "infra/kubernetes/helios-inference/deployment.yaml"
Update-Placeholder "infra/kubernetes/helios-inference/configmap.yaml"
Update-Placeholder "infra/kubernetes/helios-cost/deployment.yaml"
Update-Placeholder "infra/kubernetes/helios-cost/configmap.yaml"
Update-Placeholder "infra/kubernetes/saleor/base/configmap.yaml"

Write-Host ""
Write-Host "==============================================================================" -ForegroundColor Green
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "==============================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Review the generated .env file"
Write-Host "  2. Set your GCP project: gcloud config set project $ProjectId"
Write-Host "  3. Authenticate: gcloud auth application-default login"
Write-Host "  4. Create GCS bucket: gcloud storage buckets create gs://helios-models-$ProjectId"
Write-Host "  5. Build and push images using Cloud Build"
Write-Host ""
